//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int SeatID { get; set; }
        public System.DateTime PerchaseDateTime { get; set; }
        public decimal FinalPrice { get; set; }
        public string Status { get; set; }
    
        public virtual Seats Seats { get; set; }
        public virtual Users Users { get; set; }
    }
}
