//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TovaryOrder
    {
        public int TovarID { get; set; }
        public int OrderID { get; set; }
        public int TVID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Tovary Tovary { get; set; }
    }
}
